# templates_config.py
# Путь к .docx шаблонам остаётся относительным (папка input/)
TEMPLATES = [
    {
        "path": "input/first/дневник.docx",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "student":  "ФИО",
            "group": "Группа",
            "pr_type": "ТипПрактики",
            "vidPractikiRP": "ВидПрактикаРП",
            "kurs": "Курс",
            "kafedra": "направленность (кафедра)",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            # "initialStudent": "РасшифровкаСтудента",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "RukProfOrg": "ИнициалыРукОТПредпр",
        }
    },
    {
        "path": "input/first/договор новый тз.docx",
        "out":  "Договор_новый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "RukOrgFIO": "ФИОНаучРук",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ИНН",
            # "dolj": "ДолжностьРукОТОрг",
            "org_adress": "АдрессОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            # "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "orgBossDolj" : "ДолжностьВладельцаРП",
            "OrgBossdoljIP" : "ДолжностьВладельца",
            "orgBossVP" : "ВладелецВП",
            "orgBossFIO" : "ВладелецФИО"
        }
    },
    {
        "path": "input/first/договор старый тз.docx",
        "out":  "Договор_старый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ИНН",
            "dolj": "ДолжностьРукОТОрг",
            # "org_adress": "АдресОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            # "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "orgBossFIO" : "ВладелецФИО",
            "orgBossVP" : "ВладелецВП",
            "OrgBossdoljIP" : "ДолжностьВладельца",
        }
    },
    {
        "path": "input/first/Доп.сведения.docx",
        "out":  "Доп.сведения_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "studyForm": "ФормаОбученияРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "kafedra": "направленность (кафедра)",
            "initialStudent": "ИнициалыСтудента",
            "studyFormIP" : "ФормаОбученияИП",
            "SvedOProhObuch" : "СведенияОПрохожденииЧастиОбрПрог",
            "SvedOProhUskObuch" : "СведенияОПрохожденииУскорОбуч",
            "kurs": "Курс",
        }
    },
    {
        "path": "input/first/Задание на ВКР - 1.docx",
        "out":  "Задание_на_ВКР - 1_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "kurs": "Курс",
            "group": "Группа",
            "studyForm": "ФормаОбученияРП",
            "fioDP": "ФИОДП",
            "srokSdachiVRK" : "СрокСдачиВКР",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialNauchRuk" : "ИницНаучРук",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/first/Задание на ВКР - 2.docx",
        "out":  "Задание_на_ВКР - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "fioDP": "ФИОДП",
            "group": "Группа",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
        }
    },
    {
        "path": "input/first/Заявление на АП - 2.docx",
        "out":  "Заявление на АП - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "Фамилия И.О. зав кафедры",
            "fioRP": "ФИОРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "FIONauchRuk": "ФИОНаучРук",
            "kafedraRP": "направленность (кафедра)РП",
            "DoljNauchRuk": "ДолжностьНаучРук",
            "fio": "ФИО",
            "initialStudent": "ИнициалыСтудента",
        }
    },
    {
        "path": "input/first/Заявление на размещение в ЭБС.docx",
        "out":  "Заявление на размещение в ЭБС_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "kafedraRP": "направленность (кафедра)РП",
            "Date": "СегодняшняяДата",
            "IOinitialStudent" : "ИОФамилияСтудента",
        }
    },
    {
        "path": "input/first/заявление.docx",
        "out":  "заявление_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "Фамилия И.О. зав кафедры",
            "zavKafDP": "ФИОЗавКафедройДП",
            "fioRP": "ФИОРП",
            "kurs": "Курс",
            "group": "Группа",
            "studyForm": "ФормаОбученияРП",
            "fioDP": "ФИОДП",
            "naprPodg": "направлениеПодготовки",
            "kafedra": "направленность (кафедра)",
            "vidPractikiPR": "ВидПрактикаРП",
            "pr_type": "ТипПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "strukPodr": "СтруктурноеПодразделение",
            "org_name": "БазаПрактики",
            "fioRukProfOrgVP": "ФИОРукОТПредпрВП",
            "dolj": "ДолжностьРукОТПредпр",
            "Date": "СегодняшняяДата",
            "tel": "Телефон",
            "studEmail": "emailстуд",
        }
    },
    {
        "path": "input/first/индивидуальное задание.docx",
        "out":  "индивидуальное задание_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_typeVP": "ТипПрактикиВП",
            "vidPractiki": "ВидПрактика",
            "kafedra": "направленность (кафедра)",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "RukOrgFIO": "ФИОНаучРук",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "Date": "СегодняшняяДата",
        }
    },
    {
        "path": "input/first/Каникулы.docx",
        "out":  "Каникулы_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            # "kafedraRP": "направленность (кафедра)РП",
            "kurs": "Курс",
            "studyForm": "ФормаОбученияРП",
            "kafedra": "направленность (кафедра)",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "initialStudent": "ИнициалыСтудента",
        }
    },
    {
        "path": "input/first/Ознакомительный лист.docx",
        "out":  "Ознакомительный_лист_{ФИО}_{Группа}.docx",
        "fields": {
            "initialStudent": "ИнициалыСтудента",
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
        }
    },
    {
        "path": "input/first/совместный график.docx",
        "out":  "совместный_график_{ФИО}_{Группа}.docx",
        "fields": {
            "group": "Группа",
            # "fioRP": "ФИОвРП",
            "pr_type": "ТипПрактики",
            "vidPractikiPR": "ВидПрактикаРП",
            "kurs": "Курс",
            "srokPrak11": "Дата1ЭтапаПрактики",
            "srokPrak12": "Дата2ЭтапаПрактики",
            "srokPrak13": "Дата3ЭтапаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "org_name": "БазаПрактики",
        }
    },
    {
        "path": "input/first/Титул ВКР.docx",
        "out":  "Титул_ВКР_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "group": "Группа",
            "studyFormIP" : "ФормаОбученияИП",
            "fio": "ФИО",
            "zavKafIP": "ФИОЗавКафедройИП",
            "year": "год",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialNauchRuk" : "ИницНаучРук",
        }
    },
    {
        "path": "input/first/титул отчета.docx",
        "out":  "титул_отчета_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioRukProfOrg": "ФИОРукОТПредпр",
            "RukOrgFIO": "ФИОНаучРук",
            "group": "Группа",
            "kurs": "Курс",
            "studyFormIP" : "ФормаОбученияИП",
            "fio": "ФИО",
            "year": "год",
        }
    },
    {
        "path": "input/first/характеристика.docx",
        "out":  "характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ИНН",
            "ogrn" : "ОГРН",
            "fioDP": "ФИОДП",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "strukPodr": "СтруктурноеПодразделение",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "Date": "СегодняшняяДата"
        }
    },
    # ////////////////////// Менеджмент УП Экономика //////////////////////
    {
        "path": "input/менеджмент_УП_экономика/График.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioVP" : "ФИОВП",
            "fioRP": "ФИОРП",
            "kurs": "Курс",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "RukOrg": "РукВУЗ",
            "initialStudent": "ИнициалыСтудента",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
            "org_name": "БазаПрактики",
            "initialNauchRuk" : "ИницНаучРук"
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Дневник.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "fioVP" : "ФИОВП",
            "fioRP": "ФИОРП",
            "kurs": "Курс",
            "group": "Группа",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            # "RukOrg": "РукВУЗ",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "initialRukOrg" : "ИнициалыРукОрг",
            "orgBossDolj" : "ДолжностьВладельцаРП",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Договор.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Договор_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            # "fioRukProfOrgVP": "ФИОРукОТПрофОргВП",
            "dolj": "ДолжностьРукОТОрг",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "ustavProfOrg" : "НомерУставаПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "doljInstructions" : "ДолжностныеИнструкции",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ИНН",
            "fio": "ФИО",
            "group": "Группа",
            "faktAdrProfOrg" : "ЮрАдресПрофОрг",
            "orgBossVP" : "ВладелецВП",
            "orgBoss" : "ИнициалыВладельца",
            "orgBossDolj" : "ДолжностьВладельцаРП",
            "OrgBossdoljIP" : "ДолжностьВладельца",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Заявление.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Заявление_{ФИО}_{Группа}.docx",
        "fields": {
            "studyForm": "ФормаОбученияРП",
            "kurs": "Курс",
            "fioRP": "ФИОРП",
            "stydentPhoneNum" : "телефон",
            "studemail" : "emailстуд",
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "INN": "ИНН",
            "strukPodr": "СтруктурноеПодразделение",
            "dolj": "ДолжностьРукОТПредпр",
            # "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "initialStudent": "ИнициалыСтудента",
            "monthBefPraktika" : "ДатаЗаМесяцДоНачПракт",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Инд задание.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Инд_задание_{ФИО}_{Группа}.docx",
        "fields": {
            "workObject": "ОбъектРаботы",
            "pr_type": "ТипПрактики",
            "kafedra": "направленность (кафедра)",
            "fioDP": "ФИОДП",
            "group": "Группа",
            # "tel": "телефон",
            "studEmail": "emailстуд",
            "initialRukVRK": "ИницРукВКР",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            # "RukOrg": "РукВУЗ",
            "RukOrgFIO": "ФИОНаучРук",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "Date": "СегодняшняяДата",
            "stydentPhoneNum" : "телефон",
            "studemail" : "emailстуд",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Тит лист отчета.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Тит_лист_отчета_{ФИО}_{Группа}.docx",
        "fields": {
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioRukProfOrg": "ФИОРукОТПредпр",
            "RukOrgFIO": "ФИОНаучРук",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "year": "год",
            "studyFormIP" : "ФормаОбученияИП",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Характеристика.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "strukPodr": "СтруктурноеПодразделение",
            "dolj": "ДолжностьРукОТОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "INN": "ИНН",
            "ogrn" : "ОГРН",
            "group": "Группа",
            "orgBoss" : "ИнициалыВладельца",
            "OrgBossdoljIP" : "ДолжностьВладельца",
            # "orgBossDolj" : "ДолжностьВладельцаРП",
        }
    },
    # ///////////////////////////// Психология ////////////////////////////////////
    {
        "path": "input/психология/Дневник.docx",
        "dir":  "психология",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "fioVP" : "ФИОВП",
            "kurs": "Курс",
            "group": "Группа",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "RukProfOrg": "ИнициалыРукОТПредпр",
        }
    },
    {
        "path": "input/психология/Договор.docx",
        "dir":  "психология",
        "out":  "Договор_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            # "fioRukProfOrgVP": "ФИОРукОТПрофОргВП", 
            "dolj": "ДолжностьРукОТОрг",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "ustavProfOrg" : "НомерУставаПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "doljInstructions" : "ДолжностныеИнструкции",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ИНН",
            "fio": "ФИО",
            "group": "Группа",
            # "faktAdrProfOrg" : "ЮрАдресПрофОрг",
            "orgBossVP" : "ВладелецВП",
            "orgBoss" : "ИнициалыВладельца",
            "orgBossDolj" : "ДолжностьВладельцаРП",
            "OrgBossdoljIP" : "ДолжностьВладельца",
        }
    },
    {
        "path": "input/психология/Заявление об утверждении места практики.docx",
        "dir":  "психология",
        "out":  "Заявление_об_утверждении_места_практики_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "Фамилия И.О. зав кафедры",
            "kurs": "Курс",
            "fioRP": "ФИОРП",
            "studyForm": "ФормаОбученияРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "kafedra": "направленность (кафедра)",
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioRukProfOrg": "ФИОРукОТПредпр",
            "dolj": "ДолжностьРукОТПредпр",
            "monthBefPraktika" : "ДатаЗаМесяцДоНачПракт",
            "org_name": "БазаПрактики",
        }
    },
    {
        "path": "input/психология/инд задание.docx",
        "dir":  "психология",
        "out":  "инд_задание_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_typeVP": "ТипПрактикиВП",
            "vidPractiki": "ВидПрактика",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "RukOrgFIO": "ФИОНаучРук",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",

        }
    },
    {
        "path": "input/психология/совместный график.docx",
        "dir":  "психология",
        "out":  "совместный_график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "kurs": "Курс",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "initialNauchRuk" : "ИницНаучРук",
            "initialStudent": "ИнициалыСтудента",
            "RukProfOrg": "ИнициалыРукОТПредпр",
        }
    },
    {
        "path": "input/психология/титул.docx",
        "dir":  "психология",
        "out":  "титул_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            # "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "fioRukProfOrg": "ФИОРукОТПредпр",
            "RukOrgFIO": "ФИОНаучРук",
            "group": "Группа",
            "kurs": "Курс",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "year": "год",
            "praktikaTypeRP" : "ТипПрактикиРП",
        }
    },
    {
        "path": "input/психология/характеристика.docx",
        "dir":  "психология",
        "out":  "характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "strukPodr": "СтруктурноеПодразделение",
            # "dolj": "ДолжностьРукОТОрг",
            # "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "INN": "ИНН",
            "ogrn" : "ОГРН",
            "group": "Группа",
            "RukProfOrg": "ИнициалыРукОТПредпр",
            "dolj": "ДолжностьРукОТПредпр",
            # "orgBossDolj" : "ДолжностьВладельцаРП",
            # "initialRukOrg" : "ИнициалыРукОрг",
            # "OrgBossdoljIP" : "ДолжностьВладельцаИП",
        }
    },
    # ////////////////////////////docx11//////////////////////////////
    {
        "path": "input/new_docx11/Заявление Антиплагиат +.docx",
        "dir":  "вкр",
        "out":  "Заявление_Антиплагиат_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "Фамилия И.О. зав кафедры",
            "fioRP": "ФИОРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "FIONauchRuk": "ФИОНаучРук",
            "kafedraRP": "направленность (кафедра)РП",
            "DoljNauchRuk": "ДолжностьНаучРук",
            "fio": "ФИО",
            "initialStudent": "ИнициалыСтудента",
        }
    },
    {
        "path": "input/new_docx11/Заявление на размещение ВКР_лето_2025 (1).docx",
        "dir":  "вкр",
        "out":  "Заявление_на_размещение_ВКР_лето_2025_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "group": "Группа",
            "fio": "ФИО",
            "kafedraRP": "направленность (кафедра)РП",
            "IOinitialStudent" : "ИОФамилияСтудента",
            "VKRtheme" : "темаВКР",
            "Date": "СегодняшняяДата",
            "naprPodg": "направлениеПодготовки",
        }
    },
    {
        "path": "input/new_docx11/Заявление на согласие.docx",
        "dir":  "вкр",
        "out":  "Заявление_на_согласие_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "kurs": "Курс",
            "studyForm": "ФормаОбученияРП",
            "group": "Группа",
            "kafedra": "направленность (кафедра)",
            # "profile": "ПрофильОбучения",
            "Date": "СегодняшняяДата",
            "initialStudent": "ИнициалыСтудента",
            "naprPodg": "направлениеПодготовки",
        }
    },
    {
        "path": "input/new_docx11/Каникулы.docx",
        "dir":  "вкр",
        "out":  "Каникулы_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "kurs": "Курс",
            "studyForm": "ФормаОбученияРП",
            "kafedra": "направленность (кафедра)",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "initialStudent": "ИнициалыСтудента",
        }
    },
    {
        "path": "input/new_docx11/Лист согласования ЛС.docx",
        "dir":  "вкр",
        "out":  "Лист_согласования_ЛС_{ФИО}_{Группа}.docx",
        "fields": {
            "Date": "СегодняшняяДата",
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
        }
    },
    {
        "path": "input/new_docx11/Ознакомительный лист.docx",
        "dir":  "вкр",
        "out":  "Ознакомительный_лист_{ФИО}_{Группа}.docx",
        "fields": {
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "initialStudent": "ИнициалыСтудента",
            "Date": "СегодняшняяДата",
        }
    },
]