# templates_config.py
# Путь к .docx шаблонам остаётся относительным (папка input/)
TEMPLATES = [
    {
        "path": "input/first/дневник.docx",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "student":  "ФИО",
            "group": "Группа",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "kurs": "Курс",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialStudent": "РасшифровкаСтудента",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ"
        }
    },
    {
        "path": "input/first/договор новый тз.docx",
        "out":  "Договор_новый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "ДолжностьРукОТОрг",
            "org_adress": "АдрессОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
        }
    },
    {
        "path": "input/first/договор старый тз.docx",
        "out":  "Договор_старый_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",   
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "ДолжностьРукОТОрг",
            "org_adress": "АдресОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
        }
    },
    {
        "path": "input/first/Доп.сведения.docx",
        "out":  "Доп.сведения_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "RukOrgFIO": "РукВУЗФИО",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "dolj": "ДолжностьРукОТОрг",
            "org_adress": "АдресОрганизации",
            "strukPodr": "СтруктурноеПодразделение",
            "kab": "КабинетНомер",
            "group": "Группа",
            "kafedra": "Кафедра",
            "fio": "ФИО",
            "fioRP": "ФИОвРП",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "SvedOFormStudy": "СведенияОФормеОбучения",
            "SvedOProhObuch": "СведенияОПрохЧастиОбрПрог",
            "SvedOProhUskObuch": "СведОПрохУскорОбуч",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/first/Задание на ВКР - 1.docx",
        "out":  "Задание_на_ВКР - 1_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "kurs": "Курс",
            "group": "Группа",
            "studyForm": "формыОбучения",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "fio": "ФИО",
            "fioDP": "ФИОДП",
            "initialRukVRK": "ИницРукВКР",
            "srokSdachiVRK": "СрокСдачиВКР"
        }
    },
    {
        "path": "input/first/Задание на ВКР - 2.docx",
        "out":  "Задание_на_ВКР - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "fioDP": "ФИОДП",
            "group": "Группа",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialRukVRK": "ИницРукВКР",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/first/Заявление на АП - 2.docx",
        "out":  "Заявление на АП - 2_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "ЗаведующийКафедрой",
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "НаправлениеПодготовки",
            "FIONauchRuk": "ФИОНаучРук",
            "kafedraRP": "КафедраРП",
            "doljNauchRuk": "ДолжНаучРук",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/first/Заявление на размещение в ЭБС.docx",
        "out":  "Заявление на размещение в ЭБС_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "НаправлениеПодготовки",
            "fio": "ФИО",
            "kafedra": "Кафедра",
            "Date": "СегодняшняяДата"
        }
    },
    {
        "path": "input/first/заявление.docx",
        "out":  "заявление_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "ЗаведующийКафедрой",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "strukPodr": "СтруктурноеПодразделение",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "dolj": "ДолжностьРукОТОрг",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "Date": "СегодняшняяДата",
            "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/first/индивидуальное задание.docx",
        "out":  "индивидуальное задание_{ФИО}_{Группа}.docx",
        "fields": {
            "workObject": "ОбъектРаботы",
            "pr_type": "ТипПрактики",
            "kafedra": "Кафедра",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "initialRukVRK": "ИницРукВКР",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "Date": "СегодняшняяДата",
            "fio": "ФИО",
        }
    },
    {
        "path": "input/first/Каникулы.docx",
        "out":  "Каникулы_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "fio": "ФИО",
            "initialStudent": "РасшифровкаСтудента",
            "FStud": "ФамилияСтудента"
        }
    },
    {
        "path": "input/first/Ознакомительный лист.docx",
        "out":  "Ознакомительный_лист_{ФИО}_{Группа}.docx",
        "fields": {
            "initialStudent": "РасшифровкаСтудента",
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/first/совместный график.docx",
        "out":  "совместный_график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "pr_type": "ТипПрактики",
            "vidPractikiPR": "ВидПрактикаВРП",
            "kurs": "Курс",
            "srokPrak11": "Срок11",
            "srokPrak12": "Срок12",
            "srokPrak13": "Срок13",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "initialStudent": "РасшифровкаСтудента",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "org_name": "БазаПрактики",
        }
    },
    {
        "path": "input/first/Титул ВКР.docx",
        "out":  "Титул_ВКР_{ФИО}_{Группа}.docx",
        "fields": {
            "naprPodg": "направлениеПодготовки",
            "group": "Группа",
            "studyForm": "формыОбучения",
            "fio": "ФИО",
            "zavKaf": "ЗаведующийКафедрой",
            "year": "год",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "initialRukVRK": "ИницРукВКР",
        }
    },
    {
        "path": "input/first/титул отчета.docx",
        "out":  "титул_отчета_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "RukOrgFIO": "РукВУЗФИО",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "fio": "ФИО",
            "year": "год",
        }
    },
    {
        "path": "input/first/характеристика.docx",
        "out":  "характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "org_adress": "АдрессОрганизации",
            "INN": "ОргИНН",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "Date": "СегодняшняяДата"
        }
    },
    # ////////////////////// docx10 //////////////////////
    {
        "path": "input/менеджмент_УП_экономика/График.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioVP" : "ФИОвВП",
            "kurs": "Курс",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Дневник.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "fioVP" : "ФИОвВП",
            "kurs": "Курс",
            "group": "Группа",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "initialRukOrg" : "ИнициалыРукОрг",
            "orgBossDolj" : "ДолжностьРукОрг",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Договор.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Договор_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "fioRukProfOrgVP": "ФИОРукОТПрофОргВП",
            "dolj": "ДолжностьРукОТОрг",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "ustavProfOrg" : "НомерУставаПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "doljInstructions" : "ДолжностныеИнструкции",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "fio": "ФИО",
            "group": "Группа",
            "faktAdrProfOrg" : "ФактАдрессПрофорг",
            "orgBossVP" : "РуководительОргВП",
            "orgBossDolj" : "ДолжностьРукОрг",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Заявление.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Заявление_{ФИО}_{Группа}.docx",
        "fields": {
            "studyForm": "формыОбучения",
            "kurs": "Курс",
            "fioRP": "ФИОвРП",
            "stydentPhoneNum" : "ТелефонСтудента",
            "studemail" : "ЭлПочтаСтудента",
            "praktikaTypeRP" : "ТипПрактикиРП",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "INN": "ОргИНН",
            "strukPodr": "СтруктурноеПодразделение",
            "dolj": "ДолжностьРукОТОрг",
            "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "initialStudent": "РасшифровкаСтудента",
            "monthBefPraktika" : "ДатаЗаМесяцДоНачПракт",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Инд задание.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Инд_задание_{ФИО}_{Группа}.docx",
        "fields": {
            "workObject": "ОбъектРаботы",
            "pr_type": "ТипПрактики",
            "kafedra": "Кафедра",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "initialRukVRK": "ИницРукВКР",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "RukOrgFIO": "РукВУЗФИО",
            "initialStudent": "РасшифровкаСтудента",
            "Date": "СегодняшняяДата",
            "stydentPhoneNum" : "ТелефонСтудента",
            "studemail" : "ЭлПочтаСтудента",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Тит лист отчета.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Тит_лист_отчета_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "year": "год",
        }
    },
    {
        "path": "input/менеджмент_УП_экономика/Характеристика.docx",
        "dir":  "менеджмент_УП_экономика",
        "out":  "Характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "strukPodr": "СтруктурноеПодразделение",
            "dolj": "ДолжностьРукОТОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "INN": "ОргИНН",
            "ogrn" : "ОГРН",
        }
    },
    {
        "path": "input/психология/дневник.docx",
        "dir":  "психология",
        "out":  "Дневник_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "fioVP" : "ФИОвВП",
            "kurs": "Курс",
            "group": "Группа",
            "fio": "ФИО",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "initialRukOrg" : "ИнициалыРукОрг",
            "orgBossDolj" : "ДолжностьРукОрг",
        }
    },
    {
        "path": "input/психология/Договор изменить направление обучения на посл странице.docx",
        "dir":  "психология",
        "out":  "Договор_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "fioRukProfOrgVP": "ФИОРукОТПрофОргВП",
            "dolj": "ДолжностьРукОТОрг",
            "burnOrgDate": "ДатаСозданияОрганизации",
            "ustavProfOrg" : "НомерУставаПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "doljInstructions" : "ДолжностныеИнструкции",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "INN": "ОргИНН",
            "fio": "ФИО",
            "group": "Группа",
            "faktAdrProfOrg" : "ФактАдрессПрофорг",
            "orgBossVP" : "РуководительОргВП",
            "orgBossDolj" : "ДолжностьРукОрг",
        }
    },
    {
        "path": "input/психология/Заявление об утверждении места практики.docx",
        "dir":  "психология",
        "out":  "Заявление_об_утверждении_места_практики_{ФИО}_{Группа}.docx",
        "fields": {
            "zavKaf": "ЗаведующийКафедрой",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "napravlennost" : "Направленность ",
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "dolj": "ДолжностьРукОТОрг",
            "monthBefPraktika" : "ДатаЗаМесяцДоНачПракт",
        }
    },
    {
        "path": "input/психология/инд задание.docx",
        "dir":  "психология",
        "out":  "инд_задание_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "group": "Группа",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "RukOrgFIO": "РукВУЗФИО",
            "stepenNauchRuk": "СтепеньНаучРук",
            "ZvanieNauchRuk": "ЗваниеНаучРук",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "fio": "ФИО",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",
        }
    },
    {
        "path": "input/психология/совместный график.docx",
        "dir":  "психология",
        "out":  "совместный_график_{ФИО}_{Группа}.docx",
        "fields": {
            "fioVP" : "ФИОвВП",
            "group": "Группа",
            "kurs": "Курс",
            "naprPodg": "направлениеПодготовки",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "RukOrg": "РукВУЗ",
            "initialStudent": "РасшифровкаСтудента",
            "TwodaysBefPrak" : "ДвадняДоПрактикиБуднийДень",

        }
    },
    {
        "path": "input/психология/титул.docx",
        "dir":  "психология",
        "out":  "титул_{ФИО}_{Группа}.docx",
        "fields": {
            "pr_type": "ТипПрактики",
            "vidPractiki": "ВидПрактика",
            "org_name": "БазаПрактики",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "fioRukProfOrg": "ФИОРукОТПрофОрг",
            "RukOrgFIO": "РукВУЗФИО",
            "group": "Группа",
            "kurs": "Курс",
            "naprPodg": "направлениеПодготовки",
            "fio": "ФИО",
            "year": "год",
        }
    },
    {
        "path": "input/психология/характеристика.docx",
        "dir":  "психология",
        "out":  "характеристика_{ФИО}_{Группа}.docx",
        "fields": {
            "org_name": "БазаПрактики",
            "UrAdrVUZ": "ЮрАдресПрофОрг",
            "startPracticaDate": "НачалоПрактики",
            "endPracticaDate": "КонецПрактики",
            "fioDP": "ФИОДП",
            "group": "Группа",
            "strukPodr": "СтруктурноеПодразделение",
            "dolj": "ДолжностьРукОТОрг",
            "RukProfOrg": "ИнициалыРукОТПрофОрг",
            "INN": "ОргИНН",
            "ogrn" : "ОГРН",
        }
    },
    # ////////////////////////////docx11//////////////////////////////
    {
        "path": "input/new_docx11/Заявление Антиплагиат +.docx",
        "dir":  "вкр",
        "out":  "Заявление_Антиплагиат_{ФИО}_{Группа}.docx",
        "fields": {
            "kafedra": "Кафедра",
            "zavKafDP" : "ЗавКафДП",
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "FIONauchRuk": "ФИОНаучРук",
            "doljNauchRuk": "ДолжНаучРук",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/new_docx11/Заявление на размещение ВКР_лето_2025 (1).docx",
        "dir":  "вкр",
        "out":  "Заявление_на_размещение_ВКР_лето_2025_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "fio": "ФИО",
            "kafedraRP" : "КафедраРП",
            "initialStudent": "РасшифровкаСтудента",
            "VKRtheme" : "темаВКР",
            "Date": "СегодняшняяДата",
        }
    },
    {
        "path": "input/new_docx11/Заявление на согласие.docx",
        "dir":  "вкр",
        "out":  "Заявление_на_согласие_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "profile": "ПрофильОбучения",
            "Date": "СегодняшняяДата",
            "initialStudent": "РасшифровкаСтудента",
        }
    },
    {
        "path": "input/new_docx11/Каникулы.docx",
        "dir":  "вкр",
        "out":  "Каникулы_{ФИО}_{Группа}.docx",
        "fields": {
            "fioRP": "ФИОвРП",
            "group": "Группа",
            "kurs": "Курс",
            "studyForm": "формыОбучения",
            "naprPodg": "направлениеПодготовки",
            "napravlennost" : "Направленность ",
            "tel": "телефон",
            "studEmail": "emailстуд",
            "student":  "ФИО",
            "initialStudent": "РасшифровкаСтудента",
            "Date": "СегодняшняяДата"
        }
    },
    {
        "path": "input/new_docx11/Лист согласования ЛС.docx",
        "dir":  "вкр",
        "out":  "Лист_согласования_ЛС_{ФИО}_{Группа}.docx",
        "fields": {
            "Date": "СегодняшняяДата",
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
        }
    },
    {
        "path": "input/new_docx11/Ознакомительный лист.docx",
        "dir":  "вкр",
        "out":  "Ознакомительный_лист_{ФИО}_{Группа}.docx",
        "fields": {
            "FStud": "ФамилияСтудента",
            "NStud": "ИмяСтудента",
            "OStud": "ОтчествоСтудента",
            "group": "Группа",
            "naprPodg": "направлениеПодготовки",
            "initialStudent": "РасшифровкаСтудента",
            "Date": "СегодняшняяДата",
        }
    },
]
